version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      # Railway では自動設定される。ローカル用に compose 側で定義
      DATABASE_URL: postgres://app:app@db:5432/app
      CORS_ALLOW_ORIGINS: "*"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: /bin/sh -c "python -m app.migrate && uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  db_data:
